### ISSUE TITLE
Validation of images with missing exif data values

### ISSUE THREAD

**Issue by netsensei** [VlaamseKunstcollectie/Imagehub#1]
https://github.com/VlaamseKunstcollectie/Imagehub/blob/2507d3e7fe47c40528c66c92967dcb9b98a126e8/src/ResourceSpace/Command/FillResourceSpaceCommand.php#L109

We can't exclude the possibility that images without proper exif data will be uploaded. So, we will need to require validation here: whether or not an exif tag is present in the extracted exif data.

Currently, images without exif data, will return an error when running the command

```bash
$ ./bin/console app:fill-resourcespace

In FillResourceSpaceCommand.php line 109:

  Notice: Undefined index: DocumentName

app:fill-resourcespace [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> [<folder>] [<url>]
```

When an image doesn't contain exif data and can't be validated: just skip to the next image. Logging of validation errors could be added in a later stage.

**Comment by Kitania** [comment]
I encountered the same issue a while ago, the fix I made then was to skip the EXIF-tag, rather than the entire image. So there will be missing EXIF information in ResourceSpace but at least the resource will still be uploaded, albeit with some missing metadata.

If you want me to change the code to skip the image whenever an EXIF-tag is missing, do let me know.

**Comment by Kitania** [comment]
Can we consider this issue closed or do additional changes to the code still need to be made (regarding the EXIF tags)?

**Comment by Hobbesball** [comment]
With the code that skips an EXIF tag this issue can be considered closed. Please be aware that when an exif tag is skipped, this should be reflected in the logfile. cfr. issue #10
