### ISSUE TITLE
More frontend info on Imagehub

### ISSUE THREAD

**Issue by Hobbesball** [VlaamseKunstcollectie/Imagehub#12]
**Detailed description of the issue.**
Just like on the Datahub, some more contextual information on the Symfony front page of imagehub.vlaamsekunstcollectie is needed. 

**Possible implementation**
- a count of the amount of manifests is needed on the frontpage, formatted as 'This ImageHub currently contains X IIIF manifests.'
- more information on what the Imagehub is should be put in a div under the count, reading: 
" The Imagehub is an implementation of the [IIIF](http://iiif.io) Image API and the IIIF Presentation API by the[ Vlaamse Kunstcollectie VZW](http://vlaamsekunstcollectie.be). Its goal is to serve high-quality images of the collections of Flemish Museums using the IIIF framework. It can be used to populate IIIF viewers in web applications, possibly in conjunction with serving metadata about those images using the [Datahub](http://datahub.vlaamsekunstcollectie.be)."
- The imagehub should have a navigation bar like the datahub does, with the navbar color 
 #00AC7B and a white version of the imagehub logo, attached here. 
![logo-imagehub-white](https://user-images.githubusercontent.com/22590991/60712691-dd74e300-9f17-11e9-86f7-f4d625929218.png)
- the front page should have contact information and CTA as follows: "This datahub is managed by Vlaamse Kunstcollectie. Are you interested in publishing your collections online using IIIF? Contact us via e-mail at info@vlaamsekunstcollectie.be."

**Possible alternatives**
- If the green navbar color proves to be too gaudy, you can always make it gray and use the green imagehub logo. I'll leave it to your best judgment to see what works.
![logo-imagehub-rgb](https://user-images.githubusercontent.com/22590991/60712727-f8475780-9f17-11e9-8036-4651daf70a7c.png)

**Comment by Hobbesball** [comment]
One additional thing for the navbar:
- The navbar should contain links to two additional pages, called "Imagehub" and "IIIF". Copy for those pages will follow shortly

**Comment by Hobbesball** [comment]
another addition: 
change favicon.ico to a 16x16 version of this image:
![imagehublogo](https://user-images.githubusercontent.com/22590991/60820335-8aae5c00-a1a1-11e9-971b-9820d689d13d.png)

**Comment by Hobbesball** [comment]
**additional implementation**
create a footer with 'powered by the imagehub' and a link to the imagehub github repo

**Comment by Hobbesball** [comment]
**voor @netsensei **
create NGINX config for the two extra pages 'IIIF' and 'Imagehub'

**Comment by Kitania** [comment]
Sometimes the name of the service is written as 'ImageHub', sometimes as 'Imagehub'. The Datahub is written as 'Datahub' (sometimes as 'datahub'). What casing convention will we end up using? Imagehub or ImageHub?

Note: we have added two parameters to parameters.yml.dist (service_organisation and service_organisation_website), which you'll need to add to your parameters.yml (unless you set up the Imagehub again from scratc).

**Comment by Hobbesball** [comment]
let's use the naming convention Imagehub, with only the I uppercase.

**Comment by Kitania** [comment]
Naming convention to Imagehub has been added in 0d1379c343822e5f5c361c820aac21c28b9ed392

**Comment by Hobbesball** [comment]
frontend copy has been added in 2c9f4ad  , this issue has been resolved!
