### ISSUE TITLE
Fix CORS issue in Imagehub

### ISSUE THREAD

**Issue by Hobbesball** [VlaamseKunstcollectie/Imagehub#13]
**Detailed description of the issue.**
When IIIF viewers want to request a manifest file, CORS needs to be enabled and set to `*`. 

**Additional context**
- See the spec for enabling CORS [here](https://iiif.io/api/presentation/2.1/#responses)
- currently, CORS is enabled but set to `""`

**Comment by Kitania** [comment]
Fixed in 4cb9e4f
