### ISSUE TITLE
Create a README

### ISSUE THREAD

**Issue by Hobbesball** [VlaamseKunstcollectie/Imagehub#14]
**Possible implementation**
- Create a README based on the README of the [Datahub](https://github.com/thedatahub/datahub).
- Crucial subheadings to fill out are:
    - requirements
    - install instructions
    - front-end development

**Comment by nvanderperren** [comment]
+1  (also for #11 and #10) 

yes! documentation in general would come in handy for the ones who are not familiar with PHP and also want to test (parts of) the application

**Comment by Kitania** [comment]
Partially added in cfa4163

In the following days and weeks I will make sure to further review this README and make further changes and additions where necessary

**Comment by Kitania** [comment]
The readme should be mostly done, hoping I didn't overlook anything.
