### ISSUE TITLE
bug: "related" field in manifest.json are not formatted properly

### ISSUE THREAD

**Issue by Hobbesball** [VlaamseKunstcollectie/Imagehub#15]
**Detailed description of the issue.**
the command that creates IIIF Presentation manifests adds a link to the arthub representation of the work, in the top-level "related" field, using the work PID of the object. The URL structure of the arthub omits the ".be" part of a work pid, making "mskgent.be:2008-D-1" as a work PID into "mskgent:2008-D-1". The command logic should remove the ".be" of Work PIDs before adding them to the "related" field.

**Additional context**
in [this manifest](https://imagehub.vlaamsekunstcollectie.be/iiif/2/mskgent.be:2008-D-1/manifest.json) the "related" field has the value "https://arthub.vlaamsekunstcollectie.be/nl/catalog/mskgent.be:2008-D-1". That url does not resolve, because it should point to  "https://arthub.vlaamsekunstcollectie.be/nl/catalog/mskgent:2008-D-1"
This is an artefact of how the datahub was built, and it's the only place where the ".be" is omitted in work PIDs. In any other field where the work PID is present, the ".be" should stay added.

**Comment by Kitania** [comment]
Fixed in 8964730
