### ISSUE TITLE
Link back to IIIF Manifests in LIDO XML at the end of ETL5

### ISSUE THREAD

**Issue by Hobbesball** [VlaamseKunstcollectie/Imagehub#16]
**Detailed description of the issue.**
Given that:
- a single manifest.json file should always correspond to a single LIDO XML File and a single Work PID
- there already is a link from the IIIF manifest to the LIDO XML file in the "related" field

It makes sense to also link back to the IIIF manifest in the LIDO XML file, so that both metadata files are pointing to each other and you can get from one metadata file to the other and vice versa. 

**Additional context**
referencing other resources within Lido XML happens in the ResourceWrap. you'll have to create a new ResourceSet (in AdministrativeMetadata/ResourceWrap) and link to the IIIF manifest there. That ResourceSet should then be copied into the other language versions of AdministrativeMetadata, with no changes to the content of the set. 

You will have to authenticate yourself to the Datahub you are going to write this information to. This authentication should be configurable in the ETL5 config settings. 

**Possible implementation**
One you have created a complete manifest and have validated that manifest, but before uploading the manifest to the database, take the Datahub URL corresponding to that LIDO XML file and write the Manifest.json PURL to it. 

Follow this structure when implementing IIIF manifests into LIDO: 
```
<lido:resourceWrap>

   <lido:resourceSet>

      <lido:resourceID lido:type="purl" lido:source="Imagehub">

https://imagehub.vlaamsekunstcollectie.be/iiif/2/manifesttitle/manifest.json

      </lido:resourceID>

      <lido:resourceType>

          <lido:term lido:pref="preferred">IIIF Manifest

          </lido:term>

      </lido:resourceType>

      <lido:resourceSource>

	   <lido:legalBodyName>

              <lido:appellationValue>

                   Vlaamse Kunstcollectie VZW

              </lido:appellationValue>

          </lido:legalBodyName>

      </lido:resourceSource>

   </lido:resourceSet>

</lido:resourceWrap>

```

**Comment by Kitania** [comment]
Added in 2306938861d0b4b49ffa34825310431c1867b0c9

When deploying and testing the new code, make sure you have an OAuth client set up in your local Datahub and have added the Datahub username, password and OAuth client public ID & secret into your parameters.yml.
You also need to make sure to strip the '/oai' at the end of the datahub_url parameter.
