### ISSUE TITLE
incorporate some phpleague/skeleton files into Symfony

### ISSUE THREAD

**Issue by Hobbesball** [VlaamseKunstcollectie/Imagehub#18]
**Detailed description of the issue.**
To mirror the symfony structure of the datahub, Imagehub should have some 'default' files that are part of the [phpleague/skeleton](https://github.com/thephpleague/skeleton). Cfr [the datahub ](https://github.com/thedatahub/datahub)for its implementation. 

**Possible implementation**
Important files to integrate are:
- editorconfig
- travis
- templates
    - CHANGELOG
    - CONTRIBUTING
    - LICENSE
    - PULL-REQUEST TEMPLATE

files that shouldn't be integrated are:
- composer.json
- phpunit
- scrutinizer
- styleci

**Comment by Kitania** [comment]
Added in b2448e6d2bad8e68d42d8967f5369497a4a2eb9d
