### ISSUE TITLE
doesn't detect TIFF files without extension

### ISSUE THREAD

**Issue by Hobbesball** [VlaamseKunstcollectie/Imagehub#2]
https://github.com/VlaamseKunstcollectie/Imagehub/blob/4da542c9a62637101ca71adf2017487937dfee47/src/AppBundle/ResourceSpace/Command/FillResourceSpaceCommand.php#L81

The files that will be put in the images/ folder will not have a file extension because we don't want that to show up in the manifest URL. a url of an image with a file extension would be imagehub.vlaamsekunstcollectie.be/iiif/2/testimage.TIFF/manifest, while we want our URLs to be e.g. imagehub.vlaamsekunstcollectie.be/iiif/2/testimage/manifest. 

When checking for correct file formats, don't check for file extensions like you do in this loop, but use the[ Imagemagick GetFormat](https://www.php.net/manual/en/imagick.getformat.php) function or something similar from packages.org

**Comment by Kitania** [comment]
Good catch, I've replaced the extension check with Imagick::GetImageFormat(), that seems to do the trick (see latest commit).

**Comment by netsensei** [comment]
Yup. Seems to work here too. Let's close this.
