### ISSUE TITLE
change language labels to RFC-5646 codes

### ISSUE THREAD

**Issue by Hobbesball** [VlaamseKunstcollectie/Imagehub#20]
**Detailed description of the issue.**
Universal viewer expects an extended ISO-639 language code instead of the base ISO-639 language code for localisation. The standard codes should be extended to specify region locale following RFC-5646.

**Additional context**
in practice, this means the following tags should be replaced:
nl -> nl-BE
en -> en-GB
de -> de-DE
fr -> fr-BE

**Possible implementation**
The generate-manifests command should hardcode a switch from the basic IS-639 standard in LIDO to the extended standard for manifest.json files

**Comment by Kitania** [comment]
Added in 826f3daa183525901ffb8ff91fc85cfeb3f33b92
