### ISSUE TITLE
bug: fix array to string conversion when trying to output manifest count

### ISSUE THREAD

**Issue by Hobbesball** [VlaamseKunstcollectie/Imagehub#26]
https://github.com/VlaamseKunstcollectie/Imagehub/blob/98d864e140b098f71ec2cd3507a12785230e880e/src/AppBundle/Imagehub/Command/GenerateManifestsCommand.php#L756

On the above offending line you try to output how many manifests were generated in a log. In this log you call on the array that holds all the manifests. This causes Symfony to throw an error: array to string conversion. 

Solution: initialize a new variable , e.g. 'manifestcount', and count the amount of members in the $manifests array. Call on the $manifestcount variable in your log.

**Comment by Kitania** [comment]
Fixed in d33c99d468fadaa7f5f903a9ff3ba9015372069f

Simply forgot to use count($manifests) instead of $manifests.
