### ISSUE TITLE
manifest height and width aren't always created correctly

### ISSUE THREAD

**Issue by Hobbesball** [VlaamseKunstcollectie/Imagehub#6]
In a test manifest generated on the VPS a resource and canvas had height and width = 0, resulting in an invalid canvas that didn't show the image. 

manifest in question: https://imagehub.vlaamsekunstcollectie.be/iiif/2/kmska.be:410/manifest.json

The manifest generator command should always be able to derive the height and width of a canvas and a resource from the Image API info.json file. If this isn't available, it should skip the creation of the canvas/resource, output an error, and continue with generating the rest of the manifest.

**Comment by Kitania** [comment]
Fixed in 88454f9

This was due to a flaw in the implementation when multiple images would refer to the same data PID. Image data from Cantaloupe is now fetched for each image, rather than each data PID.

**Comment by Hobbesball** [comment]
reviewed and approved
