### ISSUE TITLE
validate manifest.json files after their creation

### ISSUE THREAD

**Issue by Hobbesball** [VlaamseKunstcollectie/Imagehub#9]
**Detailed description of the issue.**
manifest.json files created by the generatemanifestscommand need to be valid following the IIIF Presentation API 2.1 specification. Manifests should be valid before being written to the imagehub database. 

**Additional context**
Since only valid manifests can successfully be consumed by IIIF viewers like Universal Viewer, the manifests we publish through imagehub need to be valid as to not create problems on the frontend for Arthub. Not all manifests should individually be validated, but validation of a sample of manifests should ensure that no fatal errors have happened throughout the pipeline. In this way, we can catch errors in metadata that might have been caused by metadata creators or changes in software before exposing invalid manifests. The manifest generation command is the last command before manifests are exposed to users, so a validation step is necessary here. 

**Possible implementation**
As a test to see if the whole ETL has run correctly, all 165 manifests should be validated. Be aware that this isn't scalable, since every validation requires a GET request. In future development we'll need to either require more detailed validation in the different steps of the pipeline so we don't need manifest validation or integrate a validation schema in our pipeline in the same way that the current [python implementation](https://github.com/IIIF/presentation-validator) validates the manifests.

The GET request should use the following endpoint: http://iiif.io/api/presentation/validator/service/validate?format=json&version=2.0&url=manifest-url-here 

If a manifest is not valid, it should not be published, and generate output in the logfile equal to the response the validator endpoint gives, including which manifest these errors are for. If the manifest is valid, it can be safely published.

**Comment by Kitania** [comment]
Sort of implemented in 4f51d12 and 2ce3717

**NOTE: you need to add the following two lines to your config/parameters.yml file before running the generate-manifests command again (the second line can be whatever you want, as long as it's present):**
`validate_manifests: false`
`validator_url: 'http://localhost:8081/validate?url='`

The external validator appears to have some sort of throttling in place, probably to prevent this sort of automated checks. I can validate two, maximum three manfiests at a time before hitting the limit, so this solution (to use GET requests) does not appear to be viable.

Implementing our own validator in PHP will certainly take a lot of time and effort and may have its own hurdles.

For now, I use the following solution:
- Download and install the Python imlementation of the validator from Github on the virtual machine
- Run it on port 8081 (8080 appears to be used by Cantaloupe) through the following command:
`python iiif-presentation-validator.py --port 8081`
- Set 'validate_manifests' in parameters.yml to 'true'
- Run the generate-manifests command. Each manifest will be validated, if invalid it will not be published. If there is no output, that means all manifests all valid. In my case, there was no output, therefore all manifests are currently valid.

**Comment by Hobbesball** [comment]
Thanks for the implementation! The workaround you used to get the python validator to work will do perfectly for now, we would remove this validation in the case where we scale up to a higher amount of manifests anyway so having it set as a flag is perfect.
